push to github registry

diff --git a/.github/workflows/docker-ci.yml b/.github/workflows/docker-ci.yml
--- a/.github/workflows/docker-ci.yml
+++ b/.github/workflows/docker-ci.yml
@@ -1,4 +1,8 @@
 name: Docker Image CI
+# Allow writing to GitHub Packages
+permissions:
+  contents: read
+  packages: write
 
 on:
   push:
@@ -12,18 +16,21 @@ jobs:
     steps:
     - uses: actions/checkout@v4
 
-    - name: Get short SHA
-      id: sha
-      run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
-
     - name: Get branch name
       id: branch
       run: |
         if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
-          echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_OUTPUT
+          BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})
         else
-          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
+          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
         fi
+
+        if [[ "$BRANCH_NAME" =~ [A-Z] ]]; then
+          echo "Error: Branch name must be lowercase"
+          exit 1
+        fi
+
+        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
 
     # Set up Docker Buildx
     - name: Set up Docker Buildx
@@ -38,15 +45,28 @@ jobs:
         restore-keys: |
           ${{ runner.os }}-buildx-
 
+    - name: Login to GitHub Container Registry
+      uses: docker/login-action@v3
+      with:
+        registry: ghcr.io
+        username: ${{ github.actor }}
+        password: ${{ secrets.GITHUB_TOKEN }}
+
+    - name: Get lowercase repository owner
+      id: owner
+      run: |
+        OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
+        echo "name=$OWNER" >> $GITHUB_OUTPUT
+
     - name: Build and tag Docker image
       uses: docker/build-push-action@v5
       with:
         context: .
-        push: false
+        push: true
         tags: |
-          squad-layer-manager:${{ steps.sha.outputs.SHA }}
-          ${{ steps.branch.outputs.BRANCH_NAME == 'main' && 'squad-layer-manager:latest' || '' }}
-          ${{ github.event_name == 'pull_request' && format('squad-layer-manager:latest-{0}', steps.branch.outputs.BRANCH_NAME) || '' }}
+          ${{ steps.branch.outputs.BRANCH_NAME == 'main' && format('ghcr.io/{0}/squad-layer-manager:latest', steps.owner.outputs.name) || '' }}
+          ${{ contains(github.ref, 'refs/tags/') && format('ghcr.io/{0}/squad-layer-manager:{1}', steps.owner.outputs.name, github.ref_name) || '' }}
+          ${{ github.event_name == 'pull_request' && format('ghcr.io/{0}/squad-layer-manager:latest-{1}', steps.owner.outputs.name, steps.branch.outputs.BRANCH_NAME) || '' }}
         cache-from: type=local,src=/tmp/.buildx-cache
         cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
 
