in progress

diff --git a/.github/workflows/docker-ci.yml b/.github/workflows/docker-ci.yml
--- a/.github/workflows/docker-ci.yml
+++ b/.github/workflows/docker-ci.yml
@@ -6,96 +6,96 @@ permissions:
 
 on:
   push:
-    branches: [ "main" ]
+    branches: ["main"]
   pull_request:
-    branches: [ "main" ]
+    branches: ["main"]
 
 jobs:
   typecheck_and_format:
-      runs-on: ubuntu-latest
-      steps:
-        - uses: actions/checkout@v4
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
 
-        - name: Setup Node
-          uses: actions/setup-node@v4
-          with:
-            node-version: '18'
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version: "18"
 
-        - name: Setup pnpm
-          uses: pnpm/action-setup@v2
-          with:
-            version: latest
+      - name: Setup pnpm
+        uses: pnpm/action-setup@v2
+        with:
+          version: latest
 
-        - name: Install dependencies
-          run: pnpm install --frozen-lockfile
+      - name: Install dependencies
+        run: pnpm install --frozen-lockfile
 
-        - name: Check formatting
-          run: pnpm prettier **/*.{ts,tsx,js} --check --plugin '@babel/plugin-proposal-explicit-resource-management'
+      - name: Check formatting
+        run: pnpm prettier **/*.{ts,tsx,js} --check --plugin '@babel/plugin-proposal-explicit-resource-management'
 
-        - name: Type check
-          run: pnpm tsc -b
+      - name: Type check
+        run: pnpm tsc -b
 
   build:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v4
+      - uses: actions/checkout@v4
 
-    - name: Get branch name
-      id: branch
-      run: |
-        if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
-          BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})
-        else
-          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
-        fi
+      - name: Get branch name
+        id: branch
+        run: |
+          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
+            BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})
+          else
+            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
+          fi
 
-        if [[ "$BRANCH_NAME" =~ [A-Z] ]]; then
-          echo "Error: Branch name must be lowercase"
-          exit 1
-        fi
+          if [[ "$BRANCH_NAME" =~ [A-Z] ]]; then
+            echo "Error: Branch name must be lowercase"
+            exit 1
+          fi
 
-        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
+          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
 
-    # Set up Docker Buildx
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v3
+      # Set up Docker Buildx
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
-    # Cache Docker layers
-    - name: Cache Docker layers
-      uses: actions/cache@v3
-      with:
-        path: /tmp/.buildx-cache
-        key: ${{ runner.os }}-buildx-${{ github.sha }}
-        restore-keys: |
-          ${{ runner.os }}-buildx-
+      # Cache Docker layers
+      - name: Cache Docker layers
+        uses: actions/cache@v3
+        with:
+          path: /tmp/.buildx-cache
+          key: ${{ runner.os }}-buildx-${{ github.sha }}
+          restore-keys: |
+            ${{ runner.os }}-buildx-
 
-    - name: Login to GitHub Container Registry
-      uses: docker/login-action@v3
-      with:
-        registry: ghcr.io
-        username: ${{ github.actor }}
-        password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: Get lowercase repository owner
-      id: owner
-      run: |
-        OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
-        echo "name=$OWNER" >> $GITHUB_OUTPUT
+      - name: Get lowercase repository owner
+        id: owner
+        run: |
+          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
+          echo "name=$OWNER" >> $GITHUB_OUTPUT
 
-    - name: Build and tag Docker image
-      uses: docker/build-push-action@v5
-      with:
-        context: .
-        push: true
-        tags: |
-          ${{ steps.branch.outputs.BRANCH_NAME == 'main' && format('ghcr.io/{0}/squad-layer-manager:latest', steps.owner.outputs.name) || '' }}
-          ${{ contains(github.ref, 'refs/tags/') && format('ghcr.io/{0}/squad-layer-manager:{1}', steps.owner.outputs.name, github.ref_name) || '' }}
-          ${{ github.event_name == 'pull_request' && format('ghcr.io/{0}/squad-layer-manager:latest-{1}', steps.owner.outputs.name, steps.branch.outputs.BRANCH_NAME) || '' }}
-        cache-from: type=local,src=/tmp/.buildx-cache
-        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
+      - name: Build and tag Docker image
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          push: true
+          tags: |
+            ${{ steps.branch.outputs.BRANCH_NAME == 'main' && format('ghcr.io/{0}/squad-layer-manager:latest', steps.owner.outputs.name) || '' }}
+            ${{ contains(github.ref, 'refs/tags/') && format('ghcr.io/{0}/squad-layer-manager:{1}', steps.owner.outputs.name, github.ref_name) || '' }}
+            ${{ github.event_name == 'pull_request' && format('ghcr.io/{0}/squad-layer-manager:latest-{1}', steps.owner.outputs.name, steps.branch.outputs.BRANCH_NAME) || '' }}
+          cache-from: type=local,src=/tmp/.buildx-cache
+          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
 
-    # Move the cache
-    - name: Move cache
-      run: |
-        rm -rf /tmp/.buildx-cache
-        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
+      # Move the cache
+      - name: Move cache
+        run: |
+          rm -rf /tmp/.buildx-cache
+          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
